image: drupalpod/drupalpod-gitpod-base:latest

tasks:
  - init: |
      .gitpod/scripts/ddev-setup.sh
      ddev drupal-install
    command: |
      curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      sudo apt-get install -y nodejs
      .gitpod/scripts/ddev-setup.sh

ports:
  - port: 2222
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 8036
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 9003
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true
